name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: random-dwi/cmake-action@v1
        with:
          cmake-version: 3.17

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test
        run: |
          cd build
          ctest -V
